#!/usr/bin/env python3
"""
Azure Cost Source Comparison Tool

This script helps identify discrepancies between:
1. Azure Cost Management CSV exports (portal data)
2. Azure Cost CLI JSON files (per-subscription data)
3. Diff text files generated by azure-cost-cli

It analyzes the differences and provides insights into why totals may not match.
"""

import csv
import json
import os
from pathlib import Path
from collections import defaultdict
from datetime import datetime
from typing import Dict, List, Tuple


class CostSourceComparator:
    def __init__(self, finops_dir: str):
        self.finops_dir = Path(finops_dir).expanduser()
        self.csv_costs = defaultdict(lambda: defaultdict(float))
        self.json_costs = defaultdict(lambda: defaultdict(float))
        self.subscription_details = {}
        
    def parse_csv_file(self, csv_path: Path) -> Dict:
        """Parse Azure Cost Management CSV export."""
        print(f"\n📊 Parsing CSV file: {csv_path.name}")
        monthly_totals = defaultdict(float)
        service_breakdown = defaultdict(lambda: defaultdict(float))
        
        try:
            with open(csv_path, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    usage_date = row.get('UsageDate', '')
                    cost_str = row.get('Cost', '0')
                    currency = row.get('Currency', 'EUR')
                    service_family = row.get('ServiceFamily', 'Unknown')
                    
                    try:
                        cost = float(cost_str)
                    except ValueError:
                        continue
                    
                    # Extract year-month
                    if usage_date:
                        year_month = usage_date[:7]  # "2025-11"
                        monthly_totals[year_month] += cost
                        service_breakdown[year_month][service_family] += cost
            
            print(f"  ✓ Found {len(monthly_totals)} months of data")
            for month, total in sorted(monthly_totals.items()):
                print(f"    {month}: {total:,.2f} EUR")
            
            return {
                'monthly_totals': dict(monthly_totals),
                'service_breakdown': dict(service_breakdown),
                'currency': currency
            }
        except Exception as e:
            print(f"  ✗ Error parsing CSV: {e}")
            return {}
    
    def parse_json_files(self) -> Dict:
        """Parse all JSON files from azure-cost-cli."""
        print(f"\n📁 Scanning for JSON files in {self.finops_dir}")
        json_files = list(self.finops_dir.rglob("*.json"))
        print(f"  Found {len(json_files)} JSON files")
        
        monthly_data = defaultdict(lambda: defaultdict(float))
        subscription_data = defaultdict(lambda: defaultdict(dict))
        
        for json_file in json_files:
            # Extract month and subscription ID from filename
            filename = json_file.name.lower()
            
            # Determine month
            month = None
            if 'november' in filename or 'nov-' in filename:
                month = '2025-11'
            elif 'december' in filename or 'dec-' in filename:
                month = '2025-12'
            elif 'september' in filename or 'sept-' in filename:
                month = '2025-09'
            elif 'october' in filename or 'oct-' in filename:
                month = '2025-10'
            
            if not month:
                continue
            
            # Extract subscription ID
            import re
            pattern = r'([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})'
            match = re.search(pattern, filename)
            sub_id = match.group(1) if match else 'unknown'
            
            try:
                with open(json_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                if 'totals' in data and 'totalCostInTimeframe' in data['totals']:
                    cost = float(data['totals']['totalCostInTimeframe'])
                    monthly_data[month][sub_id] = cost
                    subscription_data[sub_id][month] = {
                        'cost': cost,
                        'file': str(json_file.relative_to(self.finops_dir))
                    }
                    print(f"  ✓ {json_file.name}: {cost:,.2f} EUR")
            except Exception as e:
                print(f"  ✗ Error parsing {json_file.name}: {e}")
        
        return {
            'monthly_data': dict(monthly_data),
            'subscription_data': dict(subscription_data)
        }
    
    def calculate_json_totals(self, json_data: Dict) -> Dict:
        """Calculate monthly totals from JSON data."""
        monthly_totals = {}
        for month, subscriptions in json_data.get('monthly_data', {}).items():
            monthly_totals[month] = sum(subscriptions.values())
        return monthly_totals
    
    def compare_sources(self, csv_data: Dict, json_data: Dict) -> Dict:
        """Compare CSV and JSON data sources."""
        print("\n" + "="*100)
        print("COST SOURCE COMPARISON ANALYSIS")
        print("="*100)
        
        csv_totals = csv_data.get('monthly_totals', {})
        json_totals = self.calculate_json_totals(json_data)
        
        comparison = {}
        all_months = sorted(set(list(csv_totals.keys()) + list(json_totals.keys())))
        
        print(f"\n{'Month':<15} {'CSV (Portal)':<20} {'JSON (CLI)':<20} {'Difference':<20} {'% Diff':<15}")
        print("-" * 100)
        
        for month in all_months:
            csv_cost = csv_totals.get(month, 0.0)
            json_cost = json_totals.get(month, 0.0)
            diff = csv_cost - json_cost
            pct_diff = (diff / csv_cost * 100) if csv_cost != 0 else 0.0
            
            comparison[month] = {
                'csv_cost': csv_cost,
                'json_cost': json_cost,
                'difference': diff,
                'percent_diff': pct_diff
            }
            
            print(f"{month:<15} {csv_cost:>18,.2f}  {json_cost:>18,.2f}  {diff:>18,.2f}  {pct_diff:>13,.2f}%")
        
        return comparison
    
    def analyze_discrepancies(self, comparison: Dict, csv_data: Dict, json_data: Dict):
        """Analyze and explain discrepancies."""
        print("\n" + "="*100)
        print("DISCREPANCY ANALYSIS")
        print("="*100)
        
        print("\n🔍 Possible Reasons for Differences:\n")
        
        reasons = []
        
        # Check for missing subscriptions
        for month, comp in comparison.items():
            if abs(comp['percent_diff']) > 1.0:  # More than 1% difference
                reasons.append(f"• {month}: {abs(comp['percent_diff']):.2f}% difference detected")
        
        if reasons:
            print("1. SIGNIFICANT DIFFERENCES FOUND:")
            for reason in reasons:
                print(f"   {reason}")
            print()
        
        print("2. COMMON CAUSES OF DISCREPANCIES:")
        print("   • CSV includes ALL subscriptions, JSON may only include specific subscriptions")
        print("   • CSV may include marketplace charges, support plans, or reservations")
        print("   • Different cost types: Actual Cost vs Amortized Cost")
        print("   • Time zone differences in data aggregation")
        print("   • Partial month data (if current month)")
        print("   • Credits, refunds, or adjustments applied differently")
        print("   • Rounding differences in currency conversion")
        print()
        
        print("3. DATA SCOPE COMPARISON:")
        csv_months = set(csv_data.get('monthly_totals', {}).keys())
        json_months = set(json_data.get('monthly_data', {}).keys())
        
        print(f"   • CSV covers months: {', '.join(sorted(csv_months))}")
        print(f"   • JSON covers months: {', '.join(sorted(json_months))}")
        
        if csv_months - json_months:
            print(f"   • Months in CSV but not in JSON: {', '.join(sorted(csv_months - json_months))}")
        if json_months - csv_months:
            print(f"   • Months in JSON but not in CSV: {', '.join(sorted(json_months - csv_months))}")
        print()
        
        print("4. SUBSCRIPTION COVERAGE:")
        subscription_count = len(json_data.get('subscription_data', {}))
        print(f"   • JSON data includes {subscription_count} unique subscriptions")
        print(f"   • CSV data is aggregated across all subscriptions (count not available)")
        print()
        
        # Analyze service breakdown if available
        if 'service_breakdown' in csv_data:
            print("5. SERVICE FAMILY BREAKDOWN (from CSV):")
            for month in sorted(csv_data['service_breakdown'].keys())[-2:]:  # Last 2 months
                print(f"\n   {month}:")
                services = csv_data['service_breakdown'][month]
                for service, cost in sorted(services.items(), key=lambda x: x[1], reverse=True)[:10]:
                    print(f"     {service:<40} {cost:>15,.2f} EUR")
    
    def generate_recommendations(self, comparison: Dict):
        """Generate recommendations for reconciliation."""
        print("\n" + "="*100)
        print("RECOMMENDATIONS")
        print("="*100)
        print()
        
        max_diff = max((abs(c['percent_diff']) for c in comparison.values()), default=0)
        
        if max_diff < 1.0:
            print("✓ Differences are minimal (<1%). This is likely due to:")
            print("  - Rounding differences")
            print("  - Minor timing differences in data collection")
            print("  - Small adjustments or credits")
        elif max_diff < 5.0:
            print("⚠ Moderate differences detected (1-5%). Investigate:")
            print("  - Verify all subscriptions are included in JSON data")
            print("  - Check if CSV includes marketplace or support charges")
            print("  - Confirm cost type (Actual vs Amortized)")
        else:
            print("🚨 Significant differences detected (>5%). Action required:")
            print("  1. List all subscriptions in Azure portal")
            print("  2. Verify azure-cost-cli is querying ALL subscriptions")
            print("  3. Check CSV export settings (scope, cost type, filters)")
            print("  4. Compare date ranges between CSV and JSON data")
            print("  5. Review for missing subscription data in JSON files")
        
        print("\n📝 To get accurate totals:")
        print("  • Use the same cost type (Amortized Cost) in both sources")
        print("  • Ensure CSV export includes all subscriptions")
        print("  • Verify date ranges match exactly")
        print("  • Run azure-cost-cli for ALL subscriptions")
        print("  • Check for any filtered views in Cost Management portal")
        print()


def main():
    """Main execution function."""
    print("="*100)
    print("AZURE COST SOURCE COMPARISON TOOL")
    print("="*100)
    
    finops_dir = "~/Downloads/finops"
    comparator = CostSourceComparator(finops_dir)
    
    # Check if directory exists
    if not comparator.finops_dir.exists():
        print(f"\n✗ Error: Directory not found: {comparator.finops_dir}")
        return 1
    
    # Find and parse CSV file
    csv_files = list(comparator.finops_dir.glob("*.csv"))
    if not csv_files:
        print(f"\n✗ No CSV files found in {comparator.finops_dir}")
        print("  Please export cost data from Azure Cost Management + Billing")
        return 1
    
    csv_data = comparator.parse_csv_file(csv_files[0])
    
    # Parse JSON files
    json_data = comparator.parse_json_files()
    
    if not json_data.get('monthly_data'):
        print("\n✗ No JSON cost data found")
        return 1
    
    # Compare sources
    comparison = comparator.compare_sources(csv_data, json_data)
    
    # Analyze discrepancies
    comparator.analyze_discrepancies(comparison, csv_data, json_data)
    
    # Generate recommendations
    comparator.generate_recommendations(comparison)
    
    print("\n" + "="*100)
    print("END OF ANALYSIS")
    print("="*100)
    
    return 0


if __name__ == "__main__":
    exit(main())
